### ISSUE TITLE
google cloud project config's access is not restricted from unknown sources

### ISSUE THREAD

**Issue by Mohsin-Ul-Islam** [ZoraizQ/artledger#1]
I was able to connect to firebase db from my local machine using the config in file `server/server.py`. Please restrict access to your gcp resources via the mentioned api key from trusted servers (in your case container on heroku).

Is this intentional?

Heroku provides support for environment variables that will do the job in this case.

**Comment by ZoraizQ** [comment]
Thanks for pointing that out, Mohsin! Haha I had set it to public access for the project temporarily for the sake of completion and demo. 

Had some issues with deployment, but I'll definitely convert the API keys and URI to a config secret using Heroku environment variables and restrict GCP access to it as you said, once those are fixed.

Thanks for the heads up!
